// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Container, Theme, ThemePanel} from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import './theme-config.css';
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-Inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.variable}
      >
        <QueryClientProvider>
        <AuthProvider> 
      <Theme accentColor="yellow">
        {/* <ThemePanel/> */}
        <Navbar/>
        <main className="p-5">
          <Container>
        {children}
          </Container>
        </main>
        </Theme>
        </AuthProvider>
        </QueryClientProvider>

      </body>
    </html>
  );
}
